version: '3'
services:
  backend:
    build: ./app
    restart: always
    container_name: wolt_backend
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    build: ./db
    container_name: wolt_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_NAME=${TEST_DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    container_name: wolt_adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres_data:
